FROM registry.access.redhat.com/ubi9/ubi-init:9.4
RUN dnf -y up;
RUN dnf -y install httpd; dnf clean all; systemctl enable httpd;
RUN echo "Successful Web Server Test" > /var/www/html/index.html
RUN mkdir /etc/systemd/system/httpd.service.d/; echo -e '[Service]\nRestart=always' > /etc/systemd/system/httpd.service.d/httpd.conf
RUN sed -i 's/^Listen 80$/Listen 8080/' /etc/httpd/conf/httpd.conf
RUN dnf -y module install php:8.2/common; dnf clean all; systemctl enable php-fpm;
RUN dnf -y install php-mysqlnd;
COPY --from=docker.io/composer/composer:2.7.7-bin /composer /usr/local/bin/composer
RUN dnf -y install zip unzip git
RUN composer create-project --prefer-dist laravel/laravel:^11.0 /var/www/app
COPY app.conf /etc/httpd/conf.d/app.conf
RUN chown -R apache:apache /var/www/app && chmod -R 755 /var/www/app
RUN chgrp -R 0 /var/www/app && chmod -R g=u /var/www/app
EXPOSE 8080
CMD [ "/sbin/init" ]