FROM registry.access.redhat.com/ubi8/php-74:1-130

# Add application sources to a directory that the assemble script expects them
# and set permissions so that the container runs without root access
USER 0
#ADD app-src /tmp/src
RUN git clone https://github.com/bishrulhaq/Laravel-8-CRUD.git /tmp/src
RUN cp /tmp/src/.env.example /tmp/src/.env
RUN touch /tmp/src/database/database.sqlite
RUN chown -R 1001:0 /tmp/src
USER 1001

# Install the dependencies
RUN /usr/libexec/s2i/assemble

RUN php artisan migrate && php artisan db:seed --class=StockTableSeeder

# Set the default command for the resulting image
CMD /usr/libexec/s2i/run