FROM registry.access.redhat.com/ubi8/ubi-init:8.10
RUN dnf -y up;
RUN dnf -y module install php:7.4/common; dnf clean all; systemctl enable php-fpm;
RUN dnf -y install zip unzip git php-mysqlnd; dnf clean all;
COPY --from=docker.io/composer/composer:2.5.1-bin /composer /usr/local/bin/composer
COPY config/etc/php-fpm.conf /etc/php-fpm.conf
COPY config/etc/php-fpm.d/www.conf /etc/php-fpm.d/www.conf
RUN composer create-project --prefer-dist laravel/laravel:^8.0 /var/www/app
RUN chown -R apache:apache /var/www/app && chmod -R 755 /var/www/app
RUN chgrp -R 0 /var/www/app && chmod -R g=u /var/www/app
EXPOSE 9000
CMD [ "/sbin/init" ]