FROM registry.access.redhat.com/ubi8/ubi-init:8.10
RUN dnf -y install httpd; dnf clean all; systemctl enable httpd;
RUN echo "Successful Web Server Test" > /var/www/html/index.html
RUN mkdir /etc/systemd/system/httpd.service.d/; echo -e '[Service]\nRestart=always' > /etc/systemd/system/httpd.service.d/httpd.conf
RUN dnf -y module install php:7.4/common; dnf clean all; systemctl enable php-fpm;
RUN dnf -y install php-mysqlnd;
COPY --from=docker.io/composer/composer:2.5.1-bin /composer /usr/local/bin/composer
RUN dnf -y install zip unzip git
RUN composer create-project --prefer-dist laravel/laravel:^8.0 /var/www/app
COPY app.conf /etc/httpd/conf.d/app.conf
RUN chown -R apache:apache /var/www/app && chmod -R 755 /var/www/app
EXPOSE 80
CMD [ "/sbin/init" ]