FROM registry.access.redhat.com/ubi9/php-82:1-26

# Add application sources to a directory that the assemble script expects them
# and set permissions so that the container runs without root access
USER 0
#ADD app-src /tmp/src
RUN git clone https://github.com/allphptricks/laravel-11-crud.git /tmp/src
RUN cp /tmp/src/.env.example /tmp/src/.env
RUN touch /tmp/src/database/database.sqlite
RUN chown -R 1001:0 /tmp/src
USER 1001

# Install the dependencies
RUN /usr/libexec/s2i/assemble

RUN php artisan key:generate --ansi && php artisan migrate

# Set the default command for the resulting image
CMD /usr/libexec/s2i/run